// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFvKrMV8pX8bGQXcmT0MkhbPgF6zAjBrA',
    appId: '1:569542266004:web:88cd534e8617ff7a9ef881',
    messagingSenderId: '569542266004',
    projectId: 'lab3-7fdd1',
    authDomain: 'lab3-7fdd1.firebaseapp.com',
    storageBucket: 'lab3-7fdd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjGGhQ4r4vSRJeNZGzY4zK_zgdmPo8xSY',
    appId: '1:569542266004:android:60822c4d3691ca879ef881',
    messagingSenderId: '569542266004',
    projectId: 'lab3-7fdd1',
    storageBucket: 'lab3-7fdd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgiIx_BOI26WR-4CqMroZX3ULQfgYC4tk',
    appId: '1:569542266004:ios:1f3c8c5264a2a9b99ef881',
    messagingSenderId: '569542266004',
    projectId: 'lab3-7fdd1',
    storageBucket: 'lab3-7fdd1.firebasestorage.app',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgiIx_BOI26WR-4CqMroZX3ULQfgYC4tk',
    appId: '1:569542266004:ios:1f3c8c5264a2a9b99ef881',
    messagingSenderId: '569542266004',
    projectId: 'lab3-7fdd1',
    storageBucket: 'lab3-7fdd1.firebasestorage.app',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFvKrMV8pX8bGQXcmT0MkhbPgF6zAjBrA',
    appId: '1:569542266004:web:48b690c9f748dd259ef881',
    messagingSenderId: '569542266004',
    projectId: 'lab3-7fdd1',
    authDomain: 'lab3-7fdd1.firebaseapp.com',
    storageBucket: 'lab3-7fdd1.firebasestorage.app',
  );

}